//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "cosigner_op_status"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub idx: i32,
    pub cosigner_idx: i32,
    pub operation_idx: i32,
    pub ack: Option<bool>,
    pub responded_at: Option<i64>,
    pub processed_at: Option<i64>,
    pub psbt_op_file_idx: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Idx,
    CosignerIdx,
    OperationIdx,
    Ack,
    RespondedAt,
    ProcessedAt,
    PsbtOpFileIdx,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Idx,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Cosigner,
    OpFile,
    Operation,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Idx => ColumnType::Integer.def(),
            Self::CosignerIdx => ColumnType::Integer.def(),
            Self::OperationIdx => ColumnType::Integer.def(),
            Self::Ack => ColumnType::Boolean.def().null(),
            Self::RespondedAt => ColumnType::BigInteger.def().null(),
            Self::ProcessedAt => ColumnType::BigInteger.def().null(),
            Self::PsbtOpFileIdx => ColumnType::Integer.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Cosigner => Entity::belongs_to(super::cosigner::Entity)
                .from(Column::CosignerIdx)
                .to(super::cosigner::Column::Idx)
                .into(),
            Self::OpFile => Entity::belongs_to(super::op_file::Entity)
                .from(Column::PsbtOpFileIdx)
                .to(super::op_file::Column::Idx)
                .into(),
            Self::Operation => Entity::belongs_to(super::operation::Entity)
                .from(Column::OperationIdx)
                .to(super::operation::Column::Idx)
                .into(),
        }
    }
}

impl Related<super::cosigner::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cosigner.def()
    }
}

impl Related<super::op_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpFile.def()
    }
}

impl Related<super::operation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Operation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
