//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "cosigner"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub idx: i32,
    pub xpub: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Idx,
    Xpub,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Idx,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CosignerOpStatus,
    Operation,
    TransferStatus,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Idx => ColumnType::Integer.def(),
            Self::Xpub => ColumnType::String(StringLen::None).def().unique(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CosignerOpStatus => Entity::has_many(super::cosigner_op_status::Entity).into(),
            Self::Operation => Entity::has_many(super::operation::Entity).into(),
            Self::TransferStatus => Entity::has_many(super::transfer_status::Entity).into(),
        }
    }
}

impl Related<super::cosigner_op_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CosignerOpStatus.def()
    }
}

impl Related<super::operation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Operation.def()
    }
}

impl Related<super::transfer_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransferStatus.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
