//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

use crate::routes::FileType;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "op_file"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub idx: i32,
    pub file_id: String,
    pub r#type: FileType,
    pub operation_idx: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Idx,
    FileId,
    Type,
    OperationIdx,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Idx,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CosignerOpStatus,
    Operation,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Idx => ColumnType::Integer.def(),
            Self::FileId => ColumnType::String(StringLen::None).def(),
            Self::Type => ColumnType::SmallInteger.def(),
            Self::OperationIdx => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CosignerOpStatus => Entity::has_many(super::cosigner_op_status::Entity).into(),
            Self::Operation => Entity::belongs_to(super::operation::Entity)
                .from(Column::OperationIdx)
                .to(super::operation::Column::Idx)
                .into(),
        }
    }
}

impl Related<super::cosigner_op_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CosignerOpStatus.def()
    }
}

impl Related<super::operation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Operation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
