//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

use crate::routes::{OperationStatus, OperationType};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "operation"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub idx: i32,
    pub r#type: OperationType,
    pub status: OperationStatus,
    pub created_at: i64,
    pub initiator_idx: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Idx,
    Type,
    Status,
    CreatedAt,
    InitiatorIdx,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Idx,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Cosigner,
    CosignerOpStatus,
    OpFile,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Idx => ColumnType::Integer.def(),
            Self::Type => ColumnType::SmallInteger.def(),
            Self::Status => ColumnType::SmallInteger.def(),
            Self::CreatedAt => ColumnType::BigInteger.def(),
            Self::InitiatorIdx => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Cosigner => Entity::belongs_to(super::cosigner::Entity)
                .from(Column::InitiatorIdx)
                .to(super::cosigner::Column::Idx)
                .into(),
            Self::CosignerOpStatus => Entity::has_many(super::cosigner_op_status::Entity).into(),
            Self::OpFile => Entity::has_many(super::op_file::Entity).into(),
        }
    }
}

impl Related<super::cosigner::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cosigner.def()
    }
}

impl Related<super::cosigner_op_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CosignerOpStatus.def()
    }
}

impl Related<super::op_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OpFile.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
