//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "transfer_status"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub idx: i32,
    pub batch_transfer_idx: i32,
    pub cosigner_idx: i32,
    pub registered_at: i64,
    pub accepted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Idx,
    BatchTransferIdx,
    CosignerIdx,
    RegisteredAt,
    Accepted,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Idx,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Cosigner,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Idx => ColumnType::Integer.def(),
            Self::BatchTransferIdx => ColumnType::Integer.def().unique(),
            Self::CosignerIdx => ColumnType::Integer.def(),
            Self::RegisteredAt => ColumnType::BigInteger.def(),
            Self::Accepted => ColumnType::Boolean.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Cosigner => Entity::belongs_to(super::cosigner::Entity)
                .from(Column::CosignerIdx)
                .to(super::cosigner::Column::Idx)
                .into(),
        }
    }
}

impl Related<super::cosigner::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cosigner.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
